### ISSUE TITLE
Homebrew formula?

### ISSUE THREAD

**Issue by SomeoneWeird** [99designs/iamy#12]
I'd be keen to get this into homebrew, might submit a PR tomorrow if nobody has any objections.

**Comment by mtibben** [comment]
Sure thing, go for it! 
If this tool is to gain a wider audience the README should probably get expanded a bit, it's a bit brief at the moment

**Comment by orien** [comment]
Homebrew formula added in https://github.com/Homebrew/homebrew-core/pull/14665

😄

**Comment by mtibben** [comment]
Oh brilliant, thanks @orien
