### ISSUE TITLE
Error fetching S3 data

### ISSUE THREAD

**Issue by yongfei25** [99designs/iamy#19]
Hi there,

I upgraded to 2.0 and couldn't do `iamy pull` anymore. Got error:

```
iamy pull
Error fetching S3 data: Error listing buckets: Error while calling ListBuckets: MissingRegion: could not find region configuration130 <nil>
```

I know it's beta ;) I'm just keen to try the S3 bucket policy document.

**Comment by bradfeehan** [comment]
Sounds like the same issue described in https://github.com/99designs/iamy/issues/18 😁

**Comment by yongfei25** [comment]
haha! Didn't see that! I can close this now. 📦
