### ISSUE TITLE
Managed policy limits

### ISSUE THREAD

**Issue by simpsora** [99designs/iamy#21]
We've recently started managing some policies with `iamy`.  Unfortunately, customer-managed policies come with a pretty low service limit of 5:

```
$iamy push -d .
...
An error occurred (LimitExceeded) when calling the CreatePolicyVersion operation: A managed policy can have up to 5 versions. Before you create a new version, you must delete an existing version.
```

It may be possible to have this limit raised (although the IAM docs don't call it out specifically as one that can be raised).  

In any case, I wonder if `iamy`, being a tool that manages managed policies, should have some smarts to handle this case.  If so, the path of least resistance may be to first check the number of versions, and if 5 then delete the oldest version, before adding the new version.

Thoughts?

**Comment by lox** [comment]
> If so, the path of least resistance may be to first check the number of versions, and if 5 then delete the oldest version, before adding the new version.

Sounds very sensible to me.

**Comment by bradfeehan** [comment]
I guess using `iamy` means everything's in version control, so deleting old versions in AWS isn't a huge deal. But I can't help but feel it would be good for this to require confirmation of some sort for destructive actions.
