### ISSUE TITLE
Take a backup of resources before deleting them

### ISSUE THREAD

**Issue by patrobinson** [99designs/iamy#24]
Sometimes we accidentally delete policies/roles when doing a `push`. It would be nice if IAMy could, optionally, take a backup of them before deleting them and drop them in a seperate directory (outside the normal account directory structure) in case this was not what was intended.

**Comment by mtibben** [comment]
Interesting. I typically pull before doing a push, and review all changes carefully before committing to the push. Perhaps we could make the changeset more obvious when resources are being removed, maybe colour it red or something? Or have a summary line in the prompt? `OK to delete 4 resoureces, add 5 resources Y/n` type of thing

**Comment by patrobinson** [comment]
> maybe colour it red or something? Or have a summary line in the prompt? OK to delete 4 resoureces, add 5 resources Y/n type of thing

I like all these ideas

**Comment by pda** [comment]
If iamy was willing to be git-aware, it could tell when it's about to delete resources that it never managed. I'd lean towards something simpler like coloured warnings on deletions etc, though.

**Comment by lox** [comment]
-1 on git aware, +1 on summary
