### ISSUE TITLE
Unreliable detection of CloudFormation-managed resources

### ISSUE THREAD

**Issue by pda** [99designs/iamy#36]
IAMy attempts to ignore resources that are part of CloudFormation stacks; they're likely to come and go, and be version controlled elsewhere (in the CloudFormation template). It does this by comparing the resources name against the [regular expression `-[A-Z0-9]{10,20}$`](https://github.com/99designs/iamy/blob/150fb63ba0caf530047b48f83e8b15d241f4b146/iamy/aws.go#L13), which matches CloudFormation-generated resource names. This is not ideal, because;

* The pattern may match resources not managed by CloudFormation.
* The pattern will not match CloudFormation resources where a name was specified, e.g. `RoleName` for an `AWS::IAM::Role`.

Unfortunately I can't see a simple way to improve this (which I imagine is how it came to be done this way). I imagine the only reliable way would be to enumerate all CloudFormation stacks first and keep a list of resource ARNs, and use that list as a filter in IAMy.

**Comment by simpsora** [comment]
This same issue exists for S3 bucket policies, and is causing us a fair amount of headache (conflicts when updating the stack and iamy code).

So far as I've seen there's no way to tell from resources in the API that were created via CF.  @mtibben did you have any thoughts on this?

**Comment by mtibben** [comment]
Yes this is a problem.

I'd like to create a mechanism for ignoring resources - perhaps a `.iamyignore` file if we express them in file paths, or probably better to express them as ARN globbing
