### ISSUE TITLE
Ignore aws-service-role?

### ISSUE THREAD

**Issue by lox** [99designs/iamy#38]
I am seeing a role synced down locally for one of my accounts:

`<account>/iam/role/aws-service-role/spot.amazonaws.com/AWSServiceRoleForEC2Spot.yaml`

I suspect it's an AWS thing? Should this be ignored?

**Comment by andrewjhumphrey** [comment]
A bunch of these are showing up, I reckon they should be ignored just like cloudformation created resources.

**Comment by jacobbednarz** [comment]
@lox @andrewjhumphrey I've taken a pass at addressing this one via #53.
