### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by elyscape** [99designs/iamy#50]
The currently-released version, [2.2.0], adds support for instance profiles. Unfortunately, as documented in #47, this functionality is broken. #48 fixed it, but there hasn't been a release since it was merged. Please make a 2.2.1 release with the fix.

[2.2.0]: https://github.com/99designs/iamy/releases/tag/v2.2.0

**Comment by mazzy89** [comment]
Could be the 2.2.1 version created please? Thank you

**Comment by mtibben** [comment]
https://github.com/99designs/iamy/releases/tag/v2.3.0 has been released. Sorry for the delay @elyscape
